# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.wesleyq.me/
title: Wesley W. Q.
email: wesley.chin0919@gmail.com
author: Wesley Wei Qian
description: > # "Wesley Wei Qian's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: whatsapp
    title: whatsapp
    url: wa.me/6283830815715
  - icon: whatsapp
    title: whatsapp²
    url: wa.me/6283890585717
  - icon: github
    title: group Zeroo Bot
    url: https://chat.whatsapp.com/E8IwFUibPjkDgilRKw6JBg
  - icon: whatsapp 
    title: kalau mau sewabot
    url: wa.me/6283890585717
  - icon: file-pdf-o
    title: resume
    url: http://www.wesleyq.me/rsc/resume.pdf
  - icon: envelope-o
    title: email
    url: mailto: yakuzaakyy@gmail.com
